### ISSUE TITLE
Add geocoding benchmarks  

### ISSUE THREAD

**Issue by danielnaumau** [traveltime-dev/traveltime-benchmarks#39]
Part of this task https://github.com/traveltime-dev/traveltime-benchmarks/issues/26

**Comment by danielnaumau** [comment]
We'll need to test different rpm limits

**Comment by arnasbr** [comment]
https://github.com/traveltime-dev/traveltime-benchmarks/pull/55

**Comment by arnasbr** [comment]
https://github.com/traveltime-dev/traveltime-benchmarks/pull/55 merged
